# Generated by Django 4.2.5 on 2023-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateField(auto_now_add=True, default='2023-09-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='haha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='now_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
