# Generated by Django 4.2.5 on 2023-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_date1_product_date2_product_is_it_okay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_it_okay',
            field=models.BooleanField(default=False),
        ),
    ]
