# Generated by Django 4.2.5 on 2023-10-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='like_users',
            field=models.ManyToManyField(related_name='like_pokemons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
