# Generated by Django 4.2.6 on 2023-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
